security:
    encoders:
        Acme\PermissionBundle\Entity\User:  
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        Main:
#            id: webservice_user_provider
            entity: { class: AcmePermissionBundle:User}

    firewalls:
        
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false
            

        secured_area:
            pattern:    ^/function
            form_login:
                login_path: login
                check_path: login_check    
                always_use_default_target_path: true
                default_target_path: /function
#                success_handler:
#                    loginSucess
                failure_handler:
                    loginFail
            logout:
                path:   logout
                target: /
                success_handler:
                    logoutSuccess
            remember_me:
                key: "%secret%"
                lifetime: 31536000 
                path: /
                domain: ~ 
    access_control:
        - { path: ^/admin, roles: ROLE_SUPER_ADMIN }